stages:
    - compilation
    - testing
    - formatting

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CC: gcc-7
    CXX: g++-7

before_script:
    - apt-get update -qq && apt-get install -y -qq software-properties-common clang-tools-5.0 clang-format-5.0 cppcheck python-pygments
    - add-apt-repository ppa:ubuntu-toolchain-r/test
    - apt-get update -qq && apt-get install -y -qq cmake ninja-build libncurses5-dev python3-all-dev gcc-7 g++-7 libcurl4-openssl-dev

#######################
# Compilation targets #
#######################

cmp:gcc:
    stage: compilation
    image: ubuntu
    script:
        - mkdir build && cd build
        - cmake -DCURSES_LIBRARY=/usr/lib/x86_64-linux-gnu/libcurses.so -DCURSES_INCLUDE_PATH=/usr/include -DPYTHON_EXECUTABLE=/usr/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.6 -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so -DCMAKE_BUILD_TYPE=Debug -G Ninja ..
        - ninja
    artifacts:
        paths:
            - build
        expire_in: 3 hour

##############
# Unit tests #
##############

core:gcc:
    stage: testing
    image: ubuntu
    dependencies:
        - cmp:gcc
    script:
        - cd build
        - ctest --output-on-failure

##############
# Formatting #
##############

fmt:gcc:
    stage: formatting
    image: ubuntu
    dependencies:
        - cmp:gcc
    script:
        - cd build
        - ninja check-format
fmt:cppcheck:
    stage: formatting
    image: ubuntu
    dependencies:
        - cmp:gcc
    script:
        - cd build
        - ninja cppcheck
        - ninja cppcheck-html
    artifacts:
        paths:
            - build/cppcheck_results
        expire_in: 72 hour
