#!/usr/bin/env python
# coding: utf-8

import sys
import argparse
import libgen

# Allow these to be set when initializing?
# Read from config/args for that?
sources = (
    'libgen',

# Not yet implemented sources:
#    'sci-hub',
#    'irc',
#    'torrents'
)

def search(source, query):
    if source == "libgen":
        return libgen.search(query)
    else:
        print("Unsupported source.")
        sys.exit(2)

def main(argv):
    parser = argparse.ArgumentParser(
            description='Find books and papers online and download them. \
                         When called with no arguments, bookwyrm prints this screen and exits.')

    parser.add_argument('-a', '--author', required=False)
    parser.add_argument('-t', '--title', required=False)
    parser.add_argument('-p', '--publisher', required=False)
    parser.add_argument('-y', '--year', type=int, required=False)
    parser.add_argument('-l', '--language', required=False,
            help='Two letters denoting the item\'s language. e.g. \'en\' for English or \'sv\' for Swedish')
    parser.add_argument('-e', '--extension', required=False, help='Filename extension without period')
    parser.add_argument('-i', '--isbn', required=False)
    parser.add_argument('-d', '--doi', required=False)

    args = parser.parse_args()

    if len(argv) < 2:
        parser.print_help()

#    query = args.query
#
#    for source in sources:
#        r = search(source, query)

if __name__ == '__main__':
    sys.exit(main(sys.argv))

